cd ..
currentpath = pwd;
cd bpm

pathlist = {...
    fullfile('bpm'), ...
    fullfile('bpm', 'adc'), ...
    fullfile('bpm', 'clock'), ...
    fullfile('bpm', 'pickup'), ...
    fullfile('bpm', 'rffe'), ...
    fullfile('dsp'), ...
    fullfile('engunit'), ...
    };

for i = 1:length(pathlist)
    addpath(fullfile(currentpath, pathlist{i}))
end